version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - C:\Users\POTTER-2.0\Desktop\FinalProject\temp-404:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/your_database
    networks:
      - temp-404_network 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - temp-404_network  
  
  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mongodb
      - web
    command: ["pytest"]
    networks:
      - temp-404_network

networks:
  temp-404_network:  
    driver: bridge

volumes:
  mongodb-data:
