apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbuddies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugbuddies
  template:
    metadata:
      labels:
        app: bugbuddies
    spec:
      containers:
      - name: webapp
        image: kibrik47/bugbuddies:latest
        ports:
          - containerPort: 5000
