apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-dev-to-default
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: bugbuddies-dev
