apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-web
  template:
    metadata:
      labels:
        app: myapp-web
    spec:
      containers:
      - name: web
        image: kibrik47/bugbuddies:v2
        ports:
          - containerPort: 5000
